### ISSUE TITLE
model.pt

### ISSUE THREAD

**Issue by Rajiv-kumarr** [mdciri/teeth-segmentation#1]
FileNotFoundError: [Errno 2] No such file or directory: './models/checkpoint1/model.pt'

How do I get model.pt?

**Comment by mdciri** [comment]
You can find the trained model in "Releases".

**Comment by Rajiv-kumarr** [comment]
HI,
Thanks for the instant reply, I have 1 query as follows:

Why did you implement softmax function instead of sigmoid activation function in the output layer as this is a binary classification problem?(gui.py, line no. 73)

**Comment by mdciri** [comment]
Fear Rajiv,

I guess it is a habit. Anyway, the softmax function behaves like the
sigmoid when it is a binary segmentation.


Best regards,
Marco

Il giorno ven 24 mar 2023 alle ore 06:41 Rajiv-kumarr <
***@***.***> ha scritto:
